export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const SUCCESS_ALL_RECIPE = "SUCCESS_ALL_RECIPE";
export const SUCCESS_RECIPE = "SUCCESS_RECIPE";
export const SUCCESS_USERS = "SUCCESS_USERS";



export const USER_LOADING = "USER_LOADING"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_FORGOT_SUCCESS = "USER_FORGOT_SUCCESS"
export const USER_RESET_SUCCESS = "USER_RESET_SUCCESS"
export const USER_FAIL = "USER_FAIL"

export const VALID_USER_LOADING = "VALID_USER_LOADING"
export const VALID_USERDATA_GET_SUCCESS = "VALID_USERDATA_GET_SUCCESS"
export const VALID_USER_DELETE_SUCCESS = "VALID_USER_DELETE_SUCCESS"
export const VALID_USER_LOGOUT_SUCCESS = "VALID_USER_LOGOUT_SUCCESS"
export const VALID_USER_FAIL = "VALID_USER_FAIL"


export const SUCCESS_USERS_UPDATE = "SUCCESS_USERS_UPDATE";

