export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const SUCCESS_ALL_RECIPE = "SUCCESS_ALL_RECIPE";
export const SUCCESS_RECIPE = "SUCCESS_RECIPE";
export const SUCCESS_USERS = "SUCCESS_USERS";



export const USER_LOADING = "USER_LOADING"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_FORGOT_SUCCESS = "USER_FORGOT_SUCCESS"
export const USER_RESET_SUCCESS = "USER_RESET_SUCCESS"
export const USER_FAIL = "USER_FAIL"

export const VALID_USER_LOADING = "VALID_USER_LOADING"
export const LOGOUT_USER_LOADING = "LOGOUT_USER_LOADING"
export const VALID_USERRECIPE_ADD_LOADING = "VALID_USERRECIPE_ADD_LOADING"
export const VALID_USERRECIPE_ADD_SUCCESS = "VALID_USERRECIPE_ADD_SUCCESS"
export const VALID_USERDATA_GET_SUCCESS = "VALID_USERDATA_GET_SUCCESS"
export const VALID_USERECIPE_GET_SUCCESS = "VALID_USERECIPE_GET_SUCCESS"
export const VALID_USEREVIEW_GET_SUCCESS = "VALID_USEREVIEW_GET_SUCCESS"
export const VALID_USERECIPEUPDATE_SUCCESS = "VALID_USERECIPEUPDATE_SUCCESS"
export const VALID_USER_DELETE_SUCCESS = "VALID_USER_DELETE_SUCCESS"
export const VALID_USER_LOGOUT_SUCCESS = "VALID_USER_LOGOUT_SUCCESS"
export const VALID_USER_FAIL = "VALID_USER_FAIL"


export const SUCCESS_USERS_UPDATE = "SUCCESS_USERS_UPDATE";
export const SUCCESS_USERS_ADD = "SUCCESS_USERS_ADD";
export const SUCCESS_USERS_DELETE = 'SUCCESS_USERS_DELETE';

export const SUCCESS_RECIPES_COMMENT_UPDATE = "SUCCESS_RECIPES_COMMENT_UPDATE";

export const SUCCESS_RECIPES_UPDATE = "SUCCESS_RECIPES_UPDATE";
export const SUCCESS_RECIPES_ADD = "SUCCESS_RECIPES_ADD";
export const SUCCESS_RECIPES_DELETE = 'SUCCESS_RECIPES_DELETE';

export const SUCCESS_USERS_AVATAR_UPDATE = "SUCCESS_USERS_AVATAR_UPDATE";

export const SUCCESS_MAXUSERPOST = "SUCCESS_MAXUSERPOST";
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";
